---
- name: Creating user {{ username }} in {{ ansible_hostname }} | Target ===> {{ ansible_distribution }}
  ansible.builtin.user:
    name: "{{ username }}"
    comment: "User created by Ansible Automation"
    shell: "/bin/sh"
    groups: wheel
    home: "/home/{{ username }}"
    password: "{{ passuser | password_hash('sha512') }}"
... 