---

- name: Ansible Loop Simple
  hosts: poseidon
  tasks:
    - name: User | Add user
      ansible.builtin.user:
        name: "{{item}}"
        state: present
        comment: "{{item.comment}}"
        group: "sudo"
        shell: "{{item.shell}}"
      loop:
        - { name:'felipe', comment: 'S Silva', shell: '/bin/bash' }
        - { name:'eddie', comment: 'Van Halen', shell: '/bin/bash' }


...