---
- name: Ansible Loop Control
  hosts: poseidon
  tasks:
    - name: APT | Install Packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
      loop:
        - vim
        - net-tools
        - screen
      loop_control:
        pause: 3
...